method: grid
parameters:
  dataset: 
    values:
    - airbench
    - twitter_aae
    - math
    - entity_data_imputation
    - real_toxicity_prompts
    - civil_comments
    - imdb
    - boolq
    - wikifact
    - babi_qa
    - mmlu
    - truthful_qa
    - legal_support
    - synthetic_reasoning
    - quac
    - entity_matching
    - synthetic_reasoning_natural
    - bbq
    - raft
    - narrative_qa
    - commonsense
    - lsat_qa
    - bold
    - dyck_language_np3
    - combined_data
  PL:
    values: [1, 2, 3]
  D:
    values: [1, 2]
  fitting_method:
    values: [mle, em]
  amortized_question:
    values: [True, False]
  amortized_student:
    values: [True, False]
  n_layers:
    values: [2, 3, 4, 5]
  hidden_dim:
    values: [32, 64, 128]
  report_to:
    values: [wandb]
 
program: calibrate.py
project: calibration
