method: grid
parameters:
  dataset:
    values:
    - airbench
    - twitter_aae
    - math
    - entity_data_imputation
    - real_toxicity_prompts
    - civil_comments
    - imdb
    - boolq
    - wikifact
    - babi_qa
    - mmlu
    - truthful_qa
    - legal_support
    - synthetic_reasoning
    - quac
    - entity_matching
    - synthetic_reasoning_natural
    - bbq
    - raft
    - narrative_qa
    - commonsense
    - lsat_qa
    - bold
    - dyck_language_np3
program: mle_3pl_calibration.py
project: mle_3pl_calibration
