# Model for PPO finetuning
model_name_or_path: ../data/sft/lora_10epoch
use_peft: true
lora_alpha: 512
lora_r: 256
lora_dropout: 0.1
lora_target_modules: ["q_proj", "v_proj"]
output_dir: ../data/ppo/llama3-ppo

# Reward model
reward_model: http://hyperturing2:4324
discount_reward_factor: 0.99

# Dataset
query_dataset: stair-lab/airbench-ppo
ppo_epochs: 4
mini_batch_size: 2
batch_size: 2

# Hyperparameters
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 1.0e-5
save_steps: 50

max_new_tokens: 256
log_with: wandb