program: amortized_MLE_calibration.py
project: "amortized_MLE_calibration"
method: bayes
metric:
  name: test_mse
  goal: minimize
parameters:
  lr:
    distribution: uniform
    min: 1e-5
    max: 1e-2
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 1.0
  epochs:
    values: [500, 1000, 1500]
  W_init_std:
    distribution: uniform
    min: 0.001
    max: 0.1
  max_norm:
    distribution: uniform
    min: 0.1
    max: 2.0
