---
title: "CAT and random evaluation"
output: html_document
date: "2024-09-09"
---

# Load packages
```{r, message=FALSE, warning = FALSE, echo = FALSE}
library("knitr") # for rendering the RMarkdown file
library("tidyverse") # for data wrangling 
library(dplyr)
library(mirt)
library('ggpubr')
library(ggplot2)
library("catR")
library(reshape)
library(Metrics)
library(corrplot)
library(rstudioapi)
library(patchwork)
```

```{r}
inv_logit<-function(x) {
  return (1/(1+exp(-x)))
}

func.create.response <- function(b, th, np, ni) {
  th.mat<-matrix(th,np,ni,byrow=FALSE) 
  b.mat <- matrix(rep(b, np), nrow = np, byrow = TRUE)
  pr<-inv_logit(th.mat+b.mat)
  resp <- pr
  for (i in 1:ncol(resp)) {
    resp[,i]<-rbinom(nrow(resp),1,resp[,i])
  }
  return (data.frame(resp))
}
```

```{r}
set.seed(42)
np<-500

df.theta <- read_csv("../data/real/irt_result/normal/theta/all_1PL_theta.csv", col_select = 2)
df.theta <- na.omit(df.theta)
theta_mean <- mean(df.theta$F1)
theta_std <- sd(df.theta$F1)
theta <- rnorm(np, mean = theta_mean, sd = theta_std)

df.b <- read_csv("../data/real/irt_result/normal/Z/all_1PL_Z_clean.csv", col_select = 3)
b <- df.b$z3
ni <- length(b)

item.bank <- data.frame(
  a = rep(1, ni),
  b = b,
  c = rep(0, ni),
  d = rep(1, ni)
)

resp.sample <- func.create.response(b, theta, np, ni)
```

```{r}
func.catSim <- function(resp, item.bank, method){
  ni = length(resp)-1
  np = length(resp[[1]])
  list.thetas <- NULL
  list.se <- NULL
  list.pid <- NULL
  list.item <- NULL
  
  # define cat
  pids <- resp$pid
  resp <- resp %>% select(-pid)
  
  test <- list(method = 'ML', itemSelect = method, infoType = "Fisher")
  stop <- list(rule = 'length',thr = ni)
  final <- list(method = 'ML')
  for (i in 1:np){
    pid <- pids[i]
    random_number <- 33
    start <- list(fixItems = random_number, nrItems = 1, theta = 0)
    res <- randomCAT(itemBank = item.bank, 
                     responses = as.numeric(resp[i,]), 
                     start = start, 
                     test = test, 
                     final = final, 
                     stop = stop)
    list.thetas <- c(list.thetas, res$thetaProv)
    list.pid <- c(list.pid, rep(pid, times = ni))
    list.se <- c(list.se, res$seProv)
    list.item <- c(list.item, res$testItems)
  }
  list.trialNumBlock <- rep(1:ni, np)
  return(data.frame(pid = list.pid, 
                    trialNumTotal = list.trialNumBlock, 
                    item = list.item,
                    thetaEstimate = list.thetas, 
                    thetaSE = list.se))
}

monte.carlo.cat.simulation <- function(th.sample, item.bank, iteration){
  resp.sample <- func.create.response(item.bank$b, th.sample, np, ni)
  
  simulated_pid <- sprintf("sim_%03d", 1:np)
  df <- resp.sample %>%
    mutate(pid = simulated_pid) %>%
    relocate(pid)
  
  df.results <- NULL
  for (i in 1:iteration) {
    print(i)
    df.shuffle <- df %>% 
      sample_n(size = n(), replace = FALSE)
    
    # Calculate the midpoint
    n_rows <- nrow(df.shuffle)
    midpoint <- ceiling(n_rows / 2)

    # Split the data frame into two halves
    half1 <- df.shuffle[1:midpoint, ]
    half2 <- df.shuffle[(midpoint + 1):n_rows, ]
    
    df.mfi.real <- func.catSim(half1, item.bank, "MFI")
    df.random.real <- func.catSim(half2, item.bank, "random")
    
    df.results <- df.results %>% 
      rbind(rbind(df.mfi.real %>% add_column(variant = "adaptive"), 
          df.random.real %>% add_column(variant = "random")) %>% 
      add_column(iteration = i)) 
  }
  return (df.results)
}
```

```{r}
df.monte.carlo.results.v2 <- monte.carlo.cat.simulation(theta, item.bank, 5)
df.monte.carlo.results.v2
```

## simulation data 
```{r}
df.monte.carlo.simulation.compare <- df.monte.carlo.results.v2  %>%
   mutate(thetaEstimate = round(thetaEstimate, digits = 6)) %>%
  filter(trialNumTotal == ni) %>%
  select(pid, thetaEstimate) %>%
  dplyr :: rename(trueEstimate = thetaEstimate) %>%
  left_join(df.monte.carlo.results.v2 %>%
  mutate(thetaEstimate = round(thetaEstimate, digits = 6)))
df.monte.carlo.simulation.compare
```

```{r}
df.compare.all <- df.monte.carlo.simulation.compare %>%
  select(pid, variant, trialNumTotal, thetaEstimate, iteration, thetaSE, trueEstimate) %>%
  unique() %>%
  mutate(variant = ifelse(variant == "adaptive", "CAT", "Random"))
df.compare.all
```

```{r}
func.visualize.differences.validate.all <- function(df.compare){
  df.plot_curve <- df.compare %>%
    group_by(variant, trialNumTotal) %>%
    dplyr::summarise(sem = mean(thetaSE), 
                     reliability = empirical_rxx(as.matrix(tibble(F1 = thetaEstimate, SE_F1 = thetaSE))),
                     mse = Metrics :: rmse(trueEstimate, thetaEstimate), 
                     bias = Metrics :: bias(trueEstimate, thetaEstimate))
  return (df.plot_curve %>% ungroup())
}
```

```{r}
df.aggregrate.learning.curve.all <- func.visualize.differences.validate.all(df.compare.all) %>% 
  mutate(bias = abs(bias))
df.aggregrate.learning.curve.all
```

## Reliability
```{r fig.width=6,fig.height=6}
g.reliability.all <- ggplot(df.aggregrate.learning.curve.all, mapping = aes(x = trialNumTotal, y = reliability)) +
  geom_smooth(aes(linetype = variant), color = "black", se = FALSE, size = 3) +
  labs(x = "Number of test items", 
       y = "Reliability",
       title = "Empirical Test Reliability") +
  ylim(0,1) +
  xlim(1, ni) + 
  scale_y_continuous(breaks = round(seq(0, 1, by = 0.1),1)) +
  scale_color_manual(values=c("#8F993E", "#E05A1D")) + 
  theme(title = element_text(
        size = 36, color = "black"), 
        legend.text = element_text(size = 32), 
        legend.title = element_blank(),
        axis.text=element_text(size=36),
        plot.margin = margin(1.5,1.5,1.5,1.5, "cm"),
        panel.spacing = unit(1, "lines"), 
        panel.grid = element_line(size = 2), 
        legend.key.size = unit(4, "lines"),
        axis.title=element_text(size=36), legend.position = "none")
```

## MSE
```{r fig.width=6,fig.height=6}
g.mse.all <- ggplot(df.aggregrate.learning.curve.all, mapping = aes(x = trialNumTotal,
                     y = mse)) +
  geom_smooth(aes(linetype = variant), color = "black", se = FALSE, size = 3) +
  labs(x = "Number of test items",
       y = "Mean squared error",
       title = "Mean Squared Error") + 
  ylim(0, 1) +
  xlim(1, ni) + 
  scale_color_manual(values=c("#8F993E", "#E05A1D")) + 
  theme(title = element_text(
        size = 36, color = "black"), 
        legend.title = element_blank(),
        legend.text = element_text(size = 32), 
        axis.text=element_text(size=36),
        plot.margin = margin(1.5,1.5,1.5,1.5, "cm"),
        panel.spacing = unit(1, "lines"), 
        panel.grid = element_line(size = 2), 
        legend.key.size = unit(4, "lines"),
        axis.title=element_text(size=36), legend.position = "bottom")
``` 

## bias
```{r fig.width=6,fig.height=6}
g.bias.all <- ggplot(df.aggregrate.learning.curve.all, mapping = aes(x = trialNumTotal,
                     y = bias)) +
  geom_smooth(aes(linetype = variant), color = "black", se = FALSE, size = 3) +
  labs(x = "Number of test items",
       y = "Absoluate bias",
       title = "Absolute Bias") +
  xlim(1, ni) + 
  scale_color_manual(values=c("#8F993E", "#E05A1D")) + 
  theme(title = element_text(
        size = 36, color = "black"), 
        legend.text = element_text(size = 32), 
        legend.title = element_blank(),
        axis.text=element_text(size=36),
        plot.margin = margin(1.5,1.5,1.5,1.5, "cm"),
        panel.spacing = unit(1, "lines"), 
        panel.grid = element_line(size = 2), 
        legend.key.size = unit(4, "lines"),
        axis.title=element_text(size=36), legend.position = "none")
```

```{r fig.width=30,fig.height=12}
g.reliability.all + g.mse.all + g.bias.all

ggsave("../plot/real/catR.png")
```




