method: grid
parameters:
  dataset:
    values:
    - airbench
    - math
    - mmlu
    - wikifact
    - entity_data_imputation
    - commonsense
    - quac
    - imdb
    - bbq
    - twitter_aae
    - truthful_qa
    - legal_support
    - boolq
    - narrative_qa
    - real_toxicity_prompts
    - bold
    - babi_qa
    - synthetic_reasoning_natural
    - dyck_language_np3
    - civil_comments
    - lsat_qa
    - raft
    - entity_matching
    - synthetic_reasoning
program: hard_easy_test.py
project: hard_easy_test.py
